services:
  - type: web
    name: rshf-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHON_VERSION
        value: 3.11.4
  
  - type: web
    name: rshf-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run preview -- --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: 18.12.1
      - key: VITE_API_URL
        fromService:
          name: rshf-backend
          type: web
          envVarKey: RENDER_EXTERNAL_URL
